// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzs81e0q22kHeKwmiPsMDybWQLhoJryT0',
    appId: '1:504862035186:web:fcc8858a1eff48361a546b',
    messagingSenderId: '504862035186',
    projectId: 'manajemen-obat-3ae97',
    authDomain: 'manajemen-obat-3ae97.firebaseapp.com',
    storageBucket: 'manajemen-obat-3ae97.firebasestorage.app',
    measurementId: 'G-5XZJ8Z0BL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN8kYfUv-7Dl5TAcZsGMCXaAiR5OqKAJg',
    appId: '1:504862035186:android:5b14ad308a97e4081a546b',
    messagingSenderId: '504862035186',
    projectId: 'manajemen-obat-3ae97',
    storageBucket: 'manajemen-obat-3ae97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7b5WGjfu_zyStRhjaRfJC2UGwwKUy-0',
    appId: '1:504862035186:ios:59ba20a8ea395b9d1a546b',
    messagingSenderId: '504862035186',
    projectId: 'manajemen-obat-3ae97',
    storageBucket: 'manajemen-obat-3ae97.firebasestorage.app',
    iosBundleId: 'com.example.najwaPraktikum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw7b5WGjfu_zyStRhjaRfJC2UGwwKUy-0',
    appId: '1:504862035186:ios:59ba20a8ea395b9d1a546b',
    messagingSenderId: '504862035186',
    projectId: 'manajemen-obat-3ae97',
    storageBucket: 'manajemen-obat-3ae97.firebasestorage.app',
    iosBundleId: 'com.example.najwaPraktikum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzs81e0q22kHeKwmiPsMDybWQLhoJryT0',
    appId: '1:504862035186:web:adc234c385611a6c1a546b',
    messagingSenderId: '504862035186',
    projectId: 'manajemen-obat-3ae97',
    authDomain: 'manajemen-obat-3ae97.firebaseapp.com',
    storageBucket: 'manajemen-obat-3ae97.firebasestorage.app',
    measurementId: 'G-6M8Y4DSDVW',
  );

}